# Generated by Django 4.1.7 on 2023-03-06 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_district_manager_uuid_districtmanager_user_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=155, null=True)),
                ('store_uuid', models.UUIDField(default=uuid.uuid4)),
                ('area_code', models.CharField(max_length=155)),
                ('store_latitude', models.CharField(max_length=155)),
                ('store_longitude', models.CharField(max_length=155)),
                ('district_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.districtmanager')),
                ('marketing_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.marketingmanager')),
                ('regional_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.regionaldirector')),
            ],
        ),
    ]
