# Generated by Django 4.1.7 on 2023-03-06 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtmanager',
            old_name='district_manager_uuid',
            new_name='user_uuid',
        ),
        migrations.RenameField(
            model_name='marketingmanager',
            old_name='manager_uuid',
            new_name='user_uuid',
        ),
        migrations.AddField(
            model_name='regionaldirector',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
